## Introduction to NumPy

## Why ML uses NumPy
NumPy (Numerical Python) provides the **array**, a grid of same-type values that is far faster
than a Python list for numeric work.

- **Speed:** operations run in optimized C code, not a Python loop.
- **Vectorization:** apply one operation to a whole array at once, no explicit loop needed.
- **Foundation:** Pandas, scikit-learn, TensorFlow and PyTorch are all built on NumPy arrays.
- **Memory efficient:** stores numbers more compactly than a Python list.

In [1]:
import numpy as np
print(np.__version__)

2.5.3


In [3]:
# Array Creation (Tasks 1.13, 1.14)
a = np.array([1, 2, 3, 4, 5])          # 1D array
print(a)

b = np.array([[1, 2, 3], [4, 5, 6]])   # 2D array
print(b)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


In [4]:
zeros = np.zeros((2, 3))
ones = np.ones((3, 3))
identity = np.eye(3)
seq = np.arange(0, 10, 2)         # start, stop, step
lin = np.linspace(0, 1, 5)        # 5 evenly spaced values

print(zeros); print(ones); print(identity); print(seq); print(lin)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]


In [5]:
rng = np.random.default_rng(42)
print(rng.integers(1, 100, 5))

[ 9 77 65 44 43]


In [6]:
# Array properties (1.14)
print("Shape:", b.shape)     # (2, 3)
print("Size :", b.size)      # 6
print("Ndim :", b.ndim)      # 2
print("Dtype:", b.dtype)     # int64
print(np.array([1.5, 2]).dtype)   # float64

Shape: (2, 3)
Size : 6
Ndim : 2
Dtype: int64
float64


In [7]:
# Indexing (Task 1.15)
print(a[0])        # first element -> 1
print(a[-1])       # last element  -> 5
print(b[1, 2])      # row 1, col 2 -> 6
print(b[0][1])     # same as b[0, 1] -> 2

1
5
6
2


In [8]:
# Slicing (Task 1.16)
print(a[1:4])    # index 1 to 3 -> [2 3 4]
print(a[:3])     # first 3      -> [1 2 3]
print(a[::2])    # every 2nd    -> [1 3 5]
print(a[::-1])   # reversed     -> [5 4 3 2 1]

[2 3 4]
[1 2 3]
[1 3 5]
[5 4 3 2 1]


In [9]:
print(b[:, 1])      # column 1        -> [2 5]
print(b[0, :])      # row 0           -> [1 2 3]
print(b[0:2, 1:3])  # sub-grid        -> [[2 3] [5 6]]

[2 5]
[1 2 3]
[[2 3]
 [5 6]]


In [10]:
print(a[a > 2])    # values greater than 2 -> [3 4 5]

[3 4 5]


In [11]:
# Mathematical Operations (Task 1.17)
x = np.array([10, 20, 30])
y = np.array([1, 2, 3])

print(x + y)     # [11 22 33]
print(x - y)     # [9 18 27]
print(x * y)     # [10 40 90]
print(x / y)     # [10. 10. 10.]
print(x ** 2)    # [100 400 900]
print(x + 5)     # broadcasting: adds 5 to every element -> [15 25 35]

[11 22 33]
[ 9 18 27]
[10 40 90]
[10. 10. 10.]
[100 400 900]
[15 25 35]


In [12]:
# Statistical Operations (Task 1.18)
print("Mean  :", a.mean())     # 3.0
print("Median:", np.median(a)) # 3.0
print("Min   :", a.min())      # 1
print("Max   :", a.max())      # 5
print("Std   :", a.std())      # 1.41
print("Var   :", a.var())      # 2.0
print("Sum   :", a.sum())      # 15

Mean  : 3.0
Median: 3.0
Min   : 1
Max   : 5
Std   : 1.4142135623730951
Var   : 2.0
Sum   : 15


In [13]:
# Reshaping Arrays (Task 1.19)
arr = np.arange(1, 13)     # 12 numbers
print(arr.reshape(3, 4))   # 3 rows, 4 columns
print(arr.reshape(4, 3))   # 4 rows, 3 columns
print(arr.reshape(2, 3, 2))  # a 3D array

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
