## Task 1.20: NumPy practice exercises

In [2]:
# Basic array statistics
import numpy as np
marks = np.array([88, 92, 79, 55, 67, 91, 40])
print("Shape:", marks.shape)
print("Mean :", marks.mean())
print("Max  :", marks.max())
print("Min  :", marks.min())

Shape: (7,)
Mean : 73.14285714285714
Max  : 92
Min  : 40


In [3]:
# Filter passing students (marks >= 60)
print(marks[marks >= 60])

[88 92 79 67 91]


In [4]:
# Count how many passed and failed
passed = (marks >= 60).sum()
failed = (marks < 60).sum()
print("Passed:", passed, "| Failed:", failed)

Passed: 5 | Failed: 2


In [5]:
# Normalize temperatures between 0 and 1
temps = np.array([20, 25, 18, 30, 22])
norm = (temps - temps.min()) / (temps.max() - temps.min())
print(np.round(norm, 2))

[0.17 0.58 0.   1.   0.33]


In [6]:
# Build a scaled identity matrix and get its diagonal
m = np.eye(4) * 5
print(m)
print("Diagonal:", np.diag(m))

[[5. 0. 0. 0.]
 [0. 5. 0. 0.]
 [0. 0. 5. 0.]
 [0. 0. 0. 5.]]
Diagonal: [5. 5. 5. 5.]


In [7]:
# Row sums after reshaping
grid = np.arange(1, 21).reshape(4, 5)
print(grid)
print("Row sums:", grid.sum(axis=1))


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
Row sums: [15 40 65 90]


In [8]:
# Replace negative numbers with 0
vals = np.array([5, -3, 8, -1, 0, 12])
vals[vals < 0] = 0
print(vals)

[ 5  0  8  0  0 12]


In [9]:
# Find the index of the maximum value
sales = np.array([120, 340, 89, 560, 275])
best_day = np.argmax(sales)
print("Best day index:", best_day, "| Value:", sales[best_day])

Best day index: 3 | Value: 560


In [10]:
# Sort an array and get top 3 values
prices = np.array([450, 120, 980, 230, 610, 75])
sorted_prices = np.sort(prices)[::-1]
print("Top 3:", sorted_prices[:3])

Top 3: [980 610 450]


In [11]:
# Element-wise comparison of two arrays
this_week = np.array([200, 150, 300, 180])
last_week = np.array([180, 160, 280, 200])
print("Improved days:", this_week > last_week)
print("Total change:", (this_week - last_week).sum())

Improved days: [ True False  True False]
Total change: 10
